src/Framework/Cms/routes/web.php
<?php

Route::group(['namespace' => 'Framework\Cms\Http\Controllers', 'middleware' => ['web', 'lang'], 'prefix' => 'cms'], function() {
    Route::get('login', "UserController@showLogin")->name('cms.showLogin');
    Route::get('request/reset', "UserController@showRequestReset")->name('cms.showRequestReset');
    Route::get('reset/{token}', "UserController@showReset")->name('cms.showReset');
    Route::post('reset', "UserController@reset")->name('cms.reset');
    Route::post('request/reset', "UserController@requestReset")->name('cms.requestReset');
    Route::post('login', "UserController@login")->name('cms.login');
    Route::group(['middleware' => 'cms'], function () {
        Route::post('logout', "UserController@logout")->name('cms.logout');
        Route::get('/', "CmsController@index")->name('cms.index');

        Route::resource('users', "UserController", ['as' => 'cms']);
        Route::delete('cms/users/delete', "UserController@delete")->name('cms.users.delete');

        Route::resource('roles', "RoleController", ['as' => 'cms']);
        Route::delete('cms/roles/delete', "RoleController@delete")->name('cms.roles.delete');

        Route::resource('permissions', "PermissionController", ['as' => 'cms']);
        Route::delete('cms/permissions/delete', "PermissionController@delete")->name('cms.permissions.delete');
    });
});

src/Framework/Cms/Models/Role.php
<?php

namespace Framework\Cms\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [
        'slug'
    ];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('roleLocales', function (Builder $builder) {
            $builder->with('roleLocales');
        });
    }

    public function roleLocales()
    {
        return $this->hasMany(RoleLocale::class);
    }

    public function permissionRoles()
    {
        return $this->belongsToMany(Permission::class, 'permission_roles')->withPivot('create', 'read', 'update', 'delete');
    }

    public function getLocaleAttribute()
    {
        $locale = $this->roleLocales->where('locale_id', app('locale')->getActiveLocale()->id)->first();
        if (!$locale) {
            $locale = $this->roleLocales->where('locale_id', app('locale')->getFallbackLocale()->id)->first();
        }
        return $locale;
    }

    public function getLocaleName($locale)
    {
        $locale = $this->roleLocales->where('locale_id', $locale->id)->first();
        return $locale ? $locale->name : '';
    }

    public function hasPermission($id, $field)
    {
        $permission = $this->permissionRoles->find($id);
        return $permission ? $permission->pivot->$field : false;
    }

    public function hasAllPermissionTypes($id)
    {
        $permission = $this->permissionRoles->find($id);
        if(!$permission) {
            return false;
        }
        $pivot = $permission->pivot;
        return $pivot->create && $pivot->read && $pivot->update && $pivot->delete;
    }

    public function hasPermissionBySlug($slug, $type)
    {
        $permission = $this->permissionRoles->where('slug', $slug)->first();
        return $permission ? $permission->pivot->$type : false;
    }

    public function isSuperUser()
    {
        return $this->slug == 'super_user';
    }
}

src/Framework/Cms/Http/Controllers/RoleController.php
<?php

namespace Framework\Cms\Http\Controllers;

use Framework\Cms\Http\Requests\RoleRequest;
use Framework\Cms\Models\Permission;
use Framework\Cms\Models\Role;
use Framework\Cms\Models\RoleLocale;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\JsonResponse;

/**
 * Class RoleController
 * @package Framework\Cms\Http\Controllers
 */
class RoleController extends BaseController
{
    /**
     * Returns the role index view.
     *
     * @return Factory|View
     */
    public function index()
    {
        if ($this->isSuperUser()) {
            $roles = Role::all();
        } else {
            $roles = Role::where('slug', '!=', 'super_user')->get();
        }
        return view('cms::roles.index', compact('roles'));
    }

    /**
     * Returns the role create view.
     *
     * @return Factory|View
     */
    public function create()
    {
        $this->abortPermission('roles', 'create');
        if ($this->isSuperUser()) {
            $permissions = Permission::all();
        } else {
            $permissions = Permission::where('slug', '!=', 'permissions')->get();
        }
        return view('cms::roles.create', compact('permissions'));
    }

    /**
     * Creates a new role in the database.
     *
     * @param RoleRequest $request
     * @return RedirectResponse
     */
    public function store(RoleRequest $request)
    {
        $this->abortPermission('roles', 'create');
        $role = Role::create([
            'slug' => str_slug($request->get('name')['en'])
        ]);
        foreach (app('locale')->getLocales() as $locale) {
            if (isset($request->get("name")[$locale->code])) {
                RoleLocale::create([
                    'name' => $request->get("name")[$locale->code],
                    'role_id' => $role->id,
                    'locale_id' => $locale->id
                ]);
            }
        }
        if ($request->has('permissions')) {
            if (!$this->isSuperUser()) {
                $permissions = [];
                foreach ($request->permissions as $key => $permission) {
                    $dbPermission = Permission::find($key);
                    if ($dbPermission && $dbPermission->slug != 'permissions') {
                        $permissions[$key] = $permission;
                    }
                }
                $role->permissionRoles()->sync($permissions);
            } else {
                $role->permissionRoles()->sync($request->permissions);
            }
        }

        return redirect()->route('cms.roles.index');
    }

    /**
     * Returns the role edit view.
     *
     * @param Role $role
     * @return Factory|View
     */
    public function edit(Role $role)
    {
        $this->abortPermission('roles', 'update');
        if ($this->isSuperUser()) {
            $permissions = Permission::all();
        } else {
            $permissions = Permission::where('slug', '!=', 'permissions')->get();
        }
        return view('cms::roles.edit', compact('role', 'permissions'));
    }

    /**
     * Updates a role in the database.
     *
     * @param RoleRequest $request
     * @param Role $role
     * @return RedirectResponse
     */
    public function update(RoleRequest $request, Role $role)
    {
        $this->abortPermission('roles', 'update');
        $role->update([
            'slug' => str_slug($request->get('name')['en'])
        ]);
        foreach (app('locale')->getLocales() as $locale) {
            if (isset($request->get("name")[$locale->code])) {
                RoleLocale::updateOrCreate([
                    'role_id' => $role->id,
                    'locale_id' => $locale->id
                ],
                    [
                        'name' => $request->get("name")[$locale->code]
                    ]);
            }
        }
        if ($request->has('permissions')) {
            $permissions = [];
            foreach ($request->permissions as $key => $permission) {
                $dbPermission = Permission::find($key);
                if ($dbPermission && $dbPermission->slug != 'permissions' || $this->isSuperUser()) {
                    $permission['create'] = isset($permission['create']) ? $permission['create'] : 0;
                    $permission['read'] = isset($permission['read']) ? $permission['read'] : 0;
                    $permission['update'] = isset($permission['update']) ? $permission['update'] : 0;
                    $permission['delete'] = isset($permission['delete']) ? $permission['delete'] : 0;
                    $permissions[$key] = $permission;
                }
            }
            $role->permissionRoles()->sync($permissions);
        }
        return redirect()->route('cms.roles.index');
    }

    /**
     * Removes one role from the database.
     *
     * @param Role $role
     * @return JsonResponse
     */
    public function destroy(Role $role)
    {
        $this->abortPermission('roles', 'delete');
        if (!$this->isSuperUser() && $role->slug == 'super_user') {
            abort(404);
        }
        $role->delete();
        return response()->json(['message' => true]);
    }

    /**
     * Removes multiple roles from the database.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function delete(Request $request)
    {
        $this->abortPermission('roles', 'delete');
        if ($request->has('roles')) {
            if (!$this->isSuperUser()) {
                foreach ($request->roles as $role) {
                    $dbRole = Role::find($role);
                    if (!$dbRole->isSuperUser()) {
                        $dbRole->delete();
                    }
                }
            } else {
                Role::destroy($request->users);
            }
        }
        return redirect()->back();
    }
}

src/Framework/Cms/resources/views/roles/create.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.new'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.roles.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            @include('cms::layouts.langtabs', ['enRequired' => true])
            <form action="{{ route('cms.roles.store') }}" method="POST">
                {{ csrf_field() }}
                @include('cms::roles.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.create') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/roles/edit.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.edit'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.roles.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            @include('cms::layouts.langtabs', ['enRequired' => true])
            <form action="{{ route('cms.roles.update', $role->id) }}" method="POST">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                @include('cms::roles.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.update') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/roles/index.blade.php
@extends('cms::master')

@section('title', __('cms::page.roles.title'))

@section('content')
    <div class="content">
        @if(auth()->user()->hasPermission('roles', 'create'))
            <a href="{{ route('cms.roles.create') }}"
               class="btn btn-default pull-left">{{ __('cms::page.default.new') }}</a>
        @endif
        <form action="{{ route('cms.roles.delete') }}" method="POST">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            @if(auth()->user()->hasPermission('roles', 'delete'))
                <div class="clearfix">
                    <button class="btn btn-default pull-right"
                            v-on:click="deleteButton($event, 'true')">{{ __('cms::page.default.delete') }}
                    </button>
                </div>
            @endif
            <div class="table-wrapper">
                <table id="data-table" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="1"><input type="checkbox" v-on:change="selector($event)"></th>
                        <th>{{ __('cms::table.name') }}</th>
                        <th>{{ __('cms::table.created_at') }}</th>
                        @if(auth()->user()->hasPermission('roles', 'update'))
                            <th width="1" class="edit">{{ __('cms::table.edit') }}</th>
                        @endif
                        @if(auth()->user()->hasPermission('roles', 'delete'))
                            <th width="1" class="delete">{{ __('cms::table.delete') }}</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($roles as $role)
                        <tr>
                            <td><input type="checkbox" name="roles[]" value="{{ $role->id }}"></td>
                            <td>{{ $role->locale->name }}</td>
                            <td>{{ $role->created_at }}</td>
                            @if(auth()->user()->hasPermission('roles', 'update'))
                                <td><a href="{{ route('cms.roles.edit', $role->id) }}" class="edit-icon"><i
                                                class="glyphicon glyphicon-pencil"></i></a></td>
                            @endif
                            @if(auth()->user()->hasPermission('roles', 'delete'))
                                <td>

                                    <button type="submit" data-url="{{ route('cms.roles.destroy', $role->id) }}"
                                            class="delete-icon"
                                            v-on:click="deleteButton($event)"><i class="glyphicon glyphicon-trash"></i>
                                    </button>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </form>
    </div>
@stop