src/Framework/Cms/routes/web.php
<?php

Route::group(['namespace' => 'Framework\Cms\Http\Controllers', 'middleware' => ['web', 'lang'], 'prefix' => 'cms'], function() {
    Route::get('login', "UserController@showLogin")->name('cms.showLogin');
    Route::get('request/reset', "UserController@showRequestReset")->name('cms.showRequestReset');
    Route::get('reset/{token}', "UserController@showReset")->name('cms.showReset');
    Route::post('reset', "UserController@reset")->name('cms.reset');
    Route::post('request/reset', "UserController@requestReset")->name('cms.requestReset');
    Route::post('login', "UserController@login")->name('cms.login');
    Route::group(['middleware' => 'cms'], function () {
        Route::post('logout', "UserController@logout")->name('cms.logout');
        Route::get('/', "CmsController@index")->name('cms.index');

        Route::resource('users', "UserController", ['as' => 'cms']);
        Route::delete('cms/users/delete', "UserController@delete")->name('cms.users.delete');

        Route::resource('roles', "RoleController", ['as' => 'cms']);
        Route::delete('cms/roles/delete', "RoleController@delete")->name('cms.roles.delete');

        Route::resource('permissions', "PermissionController", ['as' => 'cms']);
        Route::delete('cms/permissions/delete', "PermissionController@delete")->name('cms.permissions.delete');
    });
});

src/Framework/Cms/Models/User.php
<?php

namespace Framework\Cms\Models;

use Framework\Cms\Mail\ResetPasswordMail;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * Class User
 * @package Framework\Cms\Models
 */
class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstName', 'lastName', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullNameAttribute()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_users');
    }

    public function hasRole($slug)
    {
        return $this->roles->where('slug', $slug)->first() ? true : false;
    }

    public function hasPermission($permission, $type)
    {
        if ($this->roles->where('slug', 'super-user')->first()) {
            return true;
        }
        foreach ($this->roles as $role) {
            if ($role->hasPermissionBySlug($permission, $type)) {
                return true;
            }
        }
        return false;
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordMail($token));
    }
}

src/Framework/Cms/Http/Controllers/UserController.php
<?php

namespace Framework\Cms\Http\Controllers;

use Framework\Cms\Http\Requests\DoResetRequest;
use Framework\Cms\Http\Requests\UserRequest;
use Framework\Cms\Http\Requests\LoginRequest;
use Framework\Cms\Http\Requests\ResetRequest;
use Framework\Cms\Models\Role;
use Framework\Cms\Models\User;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Auth\Passwords\PasswordBroker;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Illuminate\Mail\Mailer;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

//TODO CLEANUP!
class UserController extends BaseController
{
    use AuthenticatesUsers;

    protected $redirectTo = '/cms';

    public function showLogin(Request $request)
    {
        return view('cms::login.login');
    }

    public function login(LoginRequest $request)
    {
        $this->validateLogin($request);
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);
            return $this->sendLockoutResponse($request);
        }
        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }
        $this->incrementLoginAttempts($request);
        return $this->sendFailedLoginResponse($request);
    }

    public function logout()
    {
        $this->guard()->logout();
        return redirect()->route('cms.login');
    }

    public function showRequestReset()
    {
        return view('cms::login.requestReset');
    }

    public function requestReset(ResetRequest $request, User $user, Mailer $mailer, PasswordBroker $broker)
    {
        $response = $broker->sendResetLink(
            $request->only('email')
        );
        if ($response == $broker::RESET_LINK_SENT) {
            return redirect()->route('cms.login')->with(['success' => 'An email has been send!']);
        }
        return redirect()->route('cms.login')->with(['error' => 'Email could not be send please try again']);
    }

    public function showReset(Request $request, $token = null)
    {
        return view('cms::login.reset')->with(
            ['token' => $token, 'email' => $request->email]
        );
    }

    public function reset(DoResetRequest $request, PasswordBroker $broker)
    {
        $response = $broker->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'), function ($user, $password) {
            $this->resetPassword($user, $password);
        });
        if ($response == $broker::PASSWORD_RESET) {
            return redirect()->route('cms.index');
        }
        return redirect()->back()
            ->withInput($request->only('email'))
            ->with(['error' => trans($response)]);
    }

    protected function resetPassword($user, $password)
    {
        $user->password = Hash::make($password);

        $user->setRememberToken(Str::random(60));

        $user->save();

        event(new PasswordReset($user));

        $this->guard()->login($user);
    }

    public function index(User $user)
    {
        if ($this->isSuperUser()) {
            $users = $user->all();
        } else {
            $users = $user->all();
            $users = $users->filter(function ($value, $key) use ($users) {
                return !$this->isSuperUser($value);
            })->all();
        }
        return view('cms::users.index', compact('users'));
    }

    public function create()
    {
        $this->abortPermission('users', 'create');

        if ($this->isSuperUser()) {
            $roles = Role::all();
        } else {
            $roles = Role::where('slug', '!=', 'super_user')->get();
        }
        return view('cms::users.create', compact('roles'));
    }

    public function store(UserRequest $request, User $userModel)
    {
        $this->abortPermission('users', 'create');
        $user = $userModel->create([
            'firstName' => $request->firstName,
            'lastName' => $request->lastName,
            'email' => $request->email,
            'password' => bcrypt($request->password),
        ]);
        if ($request->has('roles')) {
            if (!$this->isSuperUser()) {
                $roles = [];
                foreach ($request->roles as $role) {
                    $dbRole = Role::find($role);
                    if ($dbRole && !$dbRole->isSuperUser()) {
                        $roles[] = $dbRole->id;
                    }
                }
                $user->roles()->sync($roles);
            } else {
                $user->roles()->sync($request->roles);
            }
        }
        return redirect()->route('cms.users.index');
    }

    public function edit(User $user)
    {
        $this->abortPermission('users', 'update');
        if ($this->isSuperUser()) {
            $roles = Role::all();
        } else {
            if ($this->isSuperUser($user)) {
                abort(404);
            }
            $roles = Role::where('slug', '!=', 'super_user')->get();
        }
        return view('cms::users.edit', compact('roles', 'user'));
    }

    public function update(UserRequest $request, User $user)
    {
        $this->abortPermission('users', 'update');
        if (!$this->isSuperUser() && $this->isSuperUser($user)) {
            abort(404);
        }
        if (isset($request->password)) {
            $user->update([
                'firstName' => $request->firstName,
                'lastName' => $request->lastName,
                'email' => $request->email,
                'password' => bcrypt($request->password),
            ]);
        } else {
            $user->update($request->except('password'));
        }
        if ($request->has('roles')) {
            if (!$this->isSuperUser()) {
                $roles = [];
                foreach ($request->roles as $role) {
                    $dbRole = Role::find($role);
                    if ($dbRole && !$dbRole->isSuperUser()) {
                        $roles[] = $dbRole->id;
                    }
                }
                $user->roles()->sync($roles);
            } else {
                $user->roles()->sync($request->roles);
            }
        }
        return redirect()->route('cms.users.index');
    }

    public function destroy(User $user)
    {
        $this->abortPermission('users', 'delete');
        if (!$this->isSuperUser() && $this->isSuperUser($user)) {
            abort(404);
        }
        $user->delete();
        return response()->json(['message' => true]);
    }

    public function delete(Request $request)
    {
        $this->abortPermission('users', 'delete');
        if ($request->has('users')) {
            if (!$this->isSuperUser()) {
                foreach ($request->users as $user) {
                    $dbUser = User::find($user);
                    if (!$this->isSuperUser($dbUser)) {
                        $dbUser->destroy();
                    }
                }
            } else {
                User::destroy($request->users);
            }
        }
        return redirect()->back();
    }
}

src/Framework/Cms/resources/views/users/create.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.new'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.users.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            <form action="{{ route('cms.users.store') }}" method="POST">
                {{ csrf_field() }}
                @include('cms::users.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.create') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/users/edit.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.edit'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.users.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            <form action="{{ route('cms.users.update', $user->id) }}" method="POST">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                @include('cms::users.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.update') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/users/index.blade.php
@extends('cms::master')

@section('title', __('cms::page.users.title'))

@section('content')
    <div class="content">
        @if(auth()->user()->hasPermission('users', 'create'))
            <a href="{{ route('cms.users.create') }}"
               class="btn btn-default pull-left">{{ __('cms::page.default.new') }}</a>
        @endif
        <form action="{{ route('cms.users.delete') }}" method="POST">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            @if(auth()->user()->hasPermission('users', 'delete'))
                <div class="clearfix">
                    <button class="btn btn-default pull-right"
                            v-on:click="deleteButton($event, 'true')">{{ __('cms::page.default.delete') }}
                    </button>
                </div>
            @endif
            <div class="table-wrapper">
                <table id="data-table" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="1"><input type="checkbox" v-on:change="selector($event)"></th>
                        <th>{{ __('cms::table.name') }}</th>
                        <th>{{ __('cms::table.email') }}</th>
                        <th>{{ __('cms::table.created_at') }}</th>
                        @if(auth()->user()->hasPermission('users', 'update'))
                            <th width="1">{{ __('cms::table.edit') }}</th>
                        @endif
                        @if(auth()->user()->hasPermission('users', 'delete'))
                            <th width="1">{{ __('cms::table.delete') }}</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($users as $user)
                        <tr>
                            <td><input type="checkbox" name="users[]" value="{{ $user->id }}"></td>
                            <td>{{ $user->full_name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at }}</td>
                            @if(auth()->user()->hasPermission('users', 'update'))
                            <td><a href="{{ route('cms.users.edit', $user->id) }}" class="edit-icon"><i
                                            class="glyphicon glyphicon-pencil"></i></a></td>
                            @endif
                            @if(auth()->user()->hasPermission('users', 'delete'))
                            <td>

                                <button type="submit" data-url="{{ route('cms.users.destroy', $user->id) }}"
                                        class="delete-icon"
                                        v-on:click="deleteButton($event)"><i class="glyphicon glyphicon-trash"></i>
                                </button>
                            </td>
                                @endif
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </form>
    </div>
@stop