src/Framework/Cms/routes/web.php
<?php

Route::group(['namespace' => 'Framework\Cms\Http\Controllers', 'middleware' => ['web', 'lang'], 'prefix' => 'cms'], function() {
    Route::get('login', "UserController@showLogin")->name('cms.showLogin');
    Route::get('request/reset', "UserController@showRequestReset")->name('cms.showRequestReset');
    Route::get('reset/{token}', "UserController@showReset")->name('cms.showReset');
    Route::post('reset', "UserController@reset")->name('cms.reset');
    Route::post('request/reset', "UserController@requestReset")->name('cms.requestReset');
    Route::post('login', "UserController@login")->name('cms.login');
    Route::group(['middleware' => 'cms'], function () {
        Route::post('logout', "UserController@logout")->name('cms.logout');
        Route::get('/', "CmsController@index")->name('cms.index');

        Route::resource('users', "UserController", ['as' => 'cms']);
        Route::delete('cms/users/delete', "UserController@delete")->name('cms.users.delete');

        Route::resource('roles', "RoleController", ['as' => 'cms']);
        Route::delete('cms/roles/delete', "RoleController@delete")->name('cms.roles.delete');

        Route::resource('permissions', "PermissionController", ['as' => 'cms']);
        Route::delete('cms/permissions/delete', "PermissionController@delete")->name('cms.permissions.delete');
    });
});

src/Framework/Cms/Models/Permission.php
<?php

namespace Framework\Cms\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $fillable = [
        'slug'
    ];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('permissionLocales', function (Builder $builder) {
            $builder->with('permissionLocales');
        });
    }

    public function permissionLocales()
    {
        return $this->hasMany(PermissionLocale::class);
    }

    public function getPermissionLocaleAttribute()
    {
        $locale = $this->permissionLocales->where('locale_id', app('locale')->getActiveLocale()->id)->first();
        if(!$locale) {
            $locale = $this->permissionLocales->where('locale_id', app('locale')->getFallbackLocale()->id)->first();
        }
        return $locale;
    }

    public function getLocaleName($locale)
    {
        $locale = $this->permissionLocales->where('locale_id', $locale->id)->first();
        return $locale ? $locale->name : '';
    }
}

src/Framework/Cms/Http/Controllers/PermissionController.php
<?php

namespace Framework\Cms\Http\Controllers;

use Framework\Cms\Http\Requests\PermissionRequest;
use Framework\Cms\Models\Permission;
use Framework\Cms\Models\PermissionLocale;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\JsonResponse;

/**
 * Class PermissionController
 * @package Framework\Cms\Http\Controllers
 */
class PermissionController extends BaseController
{
    /**
     * Returns the permission index view.
     *
     * @param Permission $permissionModel
     * @return Factory|View
     */
    public function index(Permission $permissionModel)
    {
        $this->abortPermission('permissions', 'read');
        $permissions = $permissionModel->all();
        return view('cms::permissions.index', compact('permissions'));
    }

    /**
     * Returns the permission create view.
     *
     * @return Factory|View
     */
    public function create()
    {
        $this->abortPermission('permissions', 'create');
        return view('cms::permissions.create');
    }

    /**
     * Stores a new Permission into the database.
     * Redirects to the permission index view.
     *
     * @param PermissionRequest $request
     * @param Permission $permissionModel
     * @param PermissionLocale $permissionLocaleModel
     * @return RedirectResponse
     */
    public function store(PermissionRequest $request, Permission $permissionModel, PermissionLocale $permissionLocaleModel)
    {
        $this->abortPermission('permissions', 'create');
        $permission = $permissionModel->create([
            'slug' => str_slug($request->get('name')['en'])
        ]);
        foreach (app('locale')->getLocales() as $locale) {
            if (isset($request->get("name")[$locale->code])) {
                $permissionLocaleModel->create([
                    'name' => $request->get("name")[$locale->code],
                    'permission_id' => $permission->id,
                    'locale_id' => $locale->id
                ]);
            }
        }
        return redirect()->route('cms.permissions.index');
    }

    /**
     * Returns the permission edit view.
     *
     * @param Permission $permission
     * @return Factory|View
     */
    public function edit(Permission $permission)
    {
        $this->abortPermission('permissions', 'update');
        return view('cms::permissions.edit', compact('permission'));
    }

    /**
     * Updates a Permission into the database.
     * Redirects to the permission index view.
     *
     * @param PermissionRequest $request
     * @param Permission $permission
     * @param PermissionLocale $permissionLocaleModel
     * @return RedirectResponse
     */
    public function update(PermissionRequest $request, Permission $permission, PermissionLocale $permissionLocaleModel)
    {
        $this->abortPermission('permissions', 'update');
        $permission->update([
            'slug' => str_slug($request->get('name')['en'])
        ]);
        foreach (app('locale')->getLocales() as $locale) {
            if (isset($request->get("name")[$locale->code])) {
                $permissionLocaleModel->updateOrCreate([
                    'permission_id' => $permission->id,
                    'locale_id' => $locale->id
                ],
                    [
                        'name' => $request->get("name")[$locale->code]
                    ]);
            }
        }
        return redirect()->route('cms.permissions.index');
    }

    /**
     * Removes one permission from the database.
     *
     * @param Permission $permission
     * @return JsonResponse
     */
    public function destroy(Permission $permission)
    {
        $this->abortPermission('permissions', 'delete');
        $permission->delete();
        return response()->json(['message' => true]);
    }

    /**
     * Deletes multiple permissions from the database.
     *
     * @param Request $request
     * @param Permission $permissionModel
     * @return RedirectResponse
     */
    public function delete(Request $request, Permission $permissionModel)
    {
        $this->abortPermission('permissions', 'delete');
        if ($request->has('permissions')) {
            $permissionModel->destroy($request->permissions);
        }
        return redirect()->back();
    }

}

src/Framework/Cms/resources/views/permissions/create.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.new'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.permissions.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            @include('cms::layouts.langtabs', ['enRequired' => true])
            <form action="{{ route('cms.permissions.store') }}" method="POST">
                {{ csrf_field() }}
                @include('cms::permissions.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.create') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/permissions/edit.blade.php
@extends('cms::master')

@section('title', __('cms::page.default.edit'))

@section('content')
    <div class="content">
        <a href="{{ route('cms.permissions.index') }}" class="btn btn-default">{{ __('cms::page.default.back') }}</a>
        <section class="language-tab">
            @include('cms::layouts.langtabs', ['enRequired' => true])
            <form action="{{ route('cms.permissions.update', $permission->id) }}" method="POST">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                @include('cms::permissions.partials.form')
                <button class="btn btn-default">{{ __('cms::page.default.update') }}</button>
            </form>

        </section>
    </div>
@stop

src/Framework/Cms/resources/views/permissions/index.blade.php
@extends('cms::master')

@section('title', __('cms::page.permissions.title'))

@section('content')
    <div class="content">
        @if(auth()->user()->hasPermission('permissions', 'create'))
        <a href="{{ route('cms.permissions.create') }}"
           class="btn btn-default pull-left">{{ __('cms::page.default.new') }}</a>
        @endif
        <form action="{{ route('cms.permissions.delete') }}" method="POST">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            @if(auth()->user()->hasPermission('permissions', 'delete'))
                <div class="clearfix">
                    <button class="btn btn-default pull-right"
                            v-on:click="deleteButton($event, 'true')">{{ __('cms::page.default.delete') }}
                    </button>
                </div>
            @endif
            <div class="table-wrapper">
                <table id="data-table" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="1"><input type="checkbox" v-on:change="selector($event)"></th>
                        <th>{{ __('cms::table.name') }}</th>
                        <th>{{ __('cms::table.created_at') }}</th>
                        @if(auth()->user()->hasPermission('permissions', 'update'))
                            <th width="1" class="edit">{{ __('cms::table.edit') }}</th>
                        @endif
                        @if(auth()->user()->hasPermission('permissions', 'delete'))

                            <th width="1" class="delete">{{ __('cms::table.delete') }}</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($permissions as $permission)
                        <tr>
                            <td><input type="checkbox" name="permissions[]" value="{{ $permission->id }}"></td>
                            <td>{{ $permission->permission_locale->name }}</td>
                            <td>{{ $permission->created_at }}</td>
                            @if(auth()->user()->hasPermission('permissions', 'update'))
                            <td><a href="{{ route('cms.permissions.edit', $permission->id) }}" class="edit-icon"><i
                                            class="glyphicon glyphicon-pencil"></i></a></td>
                            @endif
                            @if(auth()->user()->hasPermission('permissions', 'delete'))
                                <td>
                                    <button type="submit"
                                            data-url="{{ route('cms.permissions.destroy', $permission->id) }}"
                                            class="delete-icon"
                                            v-on:click="deleteButton($event)"><i class="glyphicon glyphicon-trash"></i>
                                    </button>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </form>
    </div>
@stop